version: '3.8'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NEWSAPI_KEY=${NEWSAPI_KEY}
      - COHERE_API_KEY=${COHERE_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
      - USE_PROVIDER=${USE_PROVIDER}
    volumes:
      - ./:/app
